name: flutter_application_project
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.7
  animated_text_kit: ^4.2.2
  flutter_sequence_animation: ^4.0.0
  rubber: ^1.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  flutter_progress_hud: ^2.0.2
  cloud_firestore: ^4.9.1
  intl: ^0.18.1
  image_picker: ^1.0.4
  firebase_storage: ^11.2.6
  flutter_cache_manager: ^3.3.1
  path: ^1.8.3
  geolocator: ^10.0.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  googleapis: ^11.4.0
  audioplayers: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/balanced-diet.png
    - assets/sounds/mouse-click-153941.mp3
  #  - assets/images/calendar.png
  #  - assets/images/masala-dosa.png
  